apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hello-
spec:
  pipelineSpec:
    tasks:
      - name: hello
        taskSpec:
            steps:
              - name: hello
                image: ubuntu
                script: "echo hello world!"
