name: Create production promotion pull request
on:
  push:

jobs:
  pr:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api https://api.github.com/repos/wlynch/test/contents/date.txt \
            -X "PUT" \
            -F "content=`date | base64`" \
            -F "message=`date"` \
          
