name: Signed Commit
on: [push]
jobs:
 commit:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@a47cfb0417aa3614869806bd09de3bd0be54f812
     - shell: bash
       run: |
         echo 'hello world!'

