name: Signed Commit
on: [push, workflow_dispatch]
jobs:
 commit:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@main
       with:
         repository: 
     - shell: bash
       run: |
         echo 'hello world!'

