name: Signed Commit
on: [push, workflow_dispatch]

jobs:
  commit:
    permissions:
      contents: write
      pull-requests: write
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3

  # Make changes to pull request here

  - run: |
      date > date.txt

  - name: Create Pull Request
    uses: peter-evans/create-pull-request@v4
    with:
      author: Dan Lorenc <lorenc.d@gmail.com>

