name: Signed Commit
on: [push, workflow_dispatch]

jobs:
  new_pr:
    permissions:
      id-token: write # Enable OIDC
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    name: Make a new pull request
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Change files
        shell: bash
        run: |
          date > date.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.2
        with:
          author: Dan Lorenc <lorenc.d@gmail.com>