name: Signed Commit
on: [push]
jobs:
 commit:
   permissions:
     id-token: write # Enable OIDC
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: chainguard-dev/actions/setup-gitsign@main
     - shell: bash
       run: |
         date > date.txt
         git config --global user.email "you@example.com"
         git config --global user.name "Your Name"
         git commit -am "asdf"
         git log -1
