name: Signed Commit
on: [push]
jobs:
 commit:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@40c0f37ac1ca49bdcfa5770bbfc59b6d8aa85d50
     - shell: bash
       run: |
         echo 'hello world!'

