name: Signed Commit
on: [push]
jobs:
 commit:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@1667c9c0773b71fccfd6f49da8e3e2fd8c73ac70
     - shell: bash
       run: |
         echo 'hello world!'

